### ISSUE TITLE
Exception when building LaTeX output

### ISSUE THREAD

**Issue by 0x8000-0000** [sphinx-contrib/aafig#4]
On one of my build servers, I am getting this exception when building the latex documentation using sphinx:

Extension error:
Handler <function render_aafig_images at 0x7f18d7786b80> for event 'doctree-read' threw an exception (exception: 'LaTeXBuilder' object has no attribute 'warn')
ninja: build stopped: subcommand failed.

I am using the following packages:

Name: Sphinx
Version: 3.2.1

Name: sphinxcontrib-aafig
Version: 1.0

Name: aafigure
Version: 0.6

This is strange, since on another server that I have configured some time ago, I'm not seeing the error.

What other logging can I enable to give you more details or to help solve the problem?

**Comment by llucax** [comment]
Hi @0x8000-0000, unfortunately this extension is sort of orphan, as I (the author) haven't been using Sphinx for years now.

You should be able to get more information on the error adding `-vvv` to the command-line when building the documentation (at least according to [the docs](https://www.sphinx-doc.org/en/3.x/man/sphinx-build.html?highlight=command%20line#cmdoption-sphinx-build-v), which is what I found on a quick search).

I'd be happy to accept PRs to fix anything that is broken, but I don't have time to look into it myself.

**Comment by llucax** [comment]
Also I would compare the versions of all sphinx dependencies in both servers to see why it could be working in one and failing in another one.

**Comment by 0x8000-0000** [comment]
Thank you @llucax for the -vvv hint... 

    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/aafigure/pdf.py", line 15, in <module>
         from reportlab.lib import colors
    ModuleNotFoundError: No module named 'reportlab'

and then later...

    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/aafigure/sphinxext.py", line 146, in render_aafig_images
        fname, outfn, id, extra = render_aafigure(app, text, options)
      File "/usr/local/lib/python3.6/dist-packages/aafigure/sphinxext.py", line 208, in render_aafigure
        raise AafigError(str(e))
    aafigure.sphinxext.AafigError: please install Reportlab to get PDF output support

A short pip after, it all works!
